table 17AguardandoDescarga
	lineageTag: fc8702c8-ccab-4d4e-a776-6779d1f6e736

	column NUMERO_COLETA
		dataType: int64
		formatString: 0
		lineageTag: e70f2799-bd44-446c-9ae6-d5d9aaf9f173
		summarizeBy: none
		sourceColumn: NUMERO_COLETA

		annotation SummarizationSetBy = Automatic

	column COTACAO
		dataType: int64
		formatString: 0
		lineageTag: b85e2625-98a7-4c0b-b2c8-bb46b290d61b
		summarizeBy: sum
		sourceColumn: COTACAO

		annotation SummarizationSetBy = Automatic

	column DATA_ULTIMA_OCORRENCIA
		dataType: dateTime
		formatString: Long Date
		lineageTag: ea2f8036-9bb9-4188-94a0-f08e73696fb7
		summarizeBy: none
		sourceColumn: DATA_ULTIMA_OCORRENCIA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HORA_ULTIMA_OCORRENCIA
		dataType: dateTime
		formatString: Long Time
		lineageTag: fe2ac3a3-0226-493d-88c9-a32f4699e6a4
		summarizeBy: none
		sourceColumn: HORA_ULTIMA_OCORRENCIA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column USUARIO_ULTIMA_OCORRENCIA
		dataType: string
		lineageTag: 54abebc0-02ab-495f-ad18-6d76683d8c43
		summarizeBy: none
		sourceColumn: USUARIO_ULTIMA_OCORRENCIA

		annotation SummarizationSetBy = Automatic

	column ULTIMA_OCORRENCIA
		dataType: string
		lineageTag: 8799bb83-147b-40fd-af78-2608f3024f4e
		summarizeBy: none
		sourceColumn: ULTIMA_OCORRENCIA

		annotation SummarizationSetBy = Automatic

	column CHAVE
		dataType: string
		lineageTag: e56e3026-48e2-4cee-a405-46ea8a9d41d1
		summarizeBy: none
		sourceColumn: CHAVE

		annotation SummarizationSetBy = Automatic

	column 17DataHoraEntregaRealizada
		dataType: dateTime
		formatString: General Date
		lineageTag: 6d3d33d6-1b2f-40a6-a874-90d2f197ba69
		summarizeBy: none
		sourceColumn: 17DataHoraEntregaRealizada

		annotation SummarizationSetBy = Automatic

	partition 17AguardandoDescarga = m
		mode: import
		queryGroup: 'TABELAS PADRÃO'
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\flavi\OneDrive\001\Ocorrencias\Ocorrencias - AGUARDANDO DESCARGA.xlsx"), null, true),
				    Sheet1_Sheet = Fonte{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"NUMERO_COLETA", Int64.Type}, {"COTACAO", Int64.Type}, {"DATA_ULTIMA_OCORRENCIA", type date}, {"HORA_ULTIMA_OCORRENCIA", type time}, {"USUARIO_ULTIMA_OCORRENCIA", type text}, {"ULTIMA_OCORRENCIA", type text}, {"CHAVE", type text}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Tipo Alterado", "17DataHoraEntregaRealizada", each Text.Combine({Text.From([DATA_ULTIMA_OCORRENCIA], "pt-BR"), Text.From([HORA_ULTIMA_OCORRENCIA], "pt-BR")}, " "), type text),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Mesclada Inserida",{{"17DataHoraEntregaRealizada", type datetime}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado1", {"COTACAO"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

