table 'Opentech - Acomp - Veiculos - Monitoração'
	lineageTag: 12e03e27-8cc1-498f-b4c9-53f30cde2c0c

	column 'Tipo do veículo'
		dataType: string
		lineageTag: ba09a27e-6d9b-4425-b732-3c20988eabad
		summarizeBy: none
		sourceColumn: Tipo do veículo

		annotation SummarizationSetBy = Automatic

	column Transportadora
		dataType: string
		lineageTag: 1b95d652-2ab4-48fc-b76b-04c4e70ea061
		summarizeBy: none
		sourceColumn: Transportadora

		annotation SummarizationSetBy = Automatic

	column 'Embarcador da  viagem'
		dataType: string
		lineageTag: 268b0712-62fd-49de-b159-5dc7e81e4ce3
		summarizeBy: none
		sourceColumn: Embarcador da  viagem

		annotation SummarizationSetBy = Automatic

	column 'Cliente monitoração'
		dataType: string
		lineageTag: d251e926-c3f2-40c5-95b1-49012caca969
		summarizeBy: none
		sourceColumn: Cliente monitoração

		annotation SummarizationSetBy = Automatic

	column Conjunto
		dataType: string
		lineageTag: 532575d9-5baa-41b4-bc76-3c214ad4c24c
		summarizeBy: none
		sourceColumn: Conjunto

		annotation SummarizationSetBy = Automatic

	column 'Placa veículo'
		dataType: string
		lineageTag: 6a095235-a9de-4a22-b813-1fe72ec3ebf9
		summarizeBy: none
		sourceColumn: Placa veículo

		annotation SummarizationSetBy = Automatic

	column Frota
		dataType: string
		lineageTag: c5124e2e-529f-492b-8e99-0f6e073c2164
		summarizeBy: none
		sourceColumn: Frota

		annotation SummarizationSetBy = Automatic

	column 'Placa carreta'
		dataType: string
		lineageTag: 89df1975-f6ca-4e0a-a950-dc9c35843c5b
		summarizeBy: none
		sourceColumn: Placa carreta

		annotation SummarizationSetBy = Automatic

	column 'Aut. de embarque'
		dataType: string
		lineageTag: a16229a2-d510-4c86-8c99-4e7f0b2a95c1
		summarizeBy: none
		sourceColumn: Aut. de embarque

		annotation SummarizationSetBy = Automatic

	column 'Frota carreta'
		dataType: string
		lineageTag: 355c7d42-0255-4f63-a39c-bc4a91f55f1b
		summarizeBy: none
		sourceColumn: Frota carreta

		annotation SummarizationSetBy = Automatic

	column 'Placa carreta 2'
		dataType: string
		lineageTag: 4457081f-ed95-4831-85e3-d1d14633c40c
		summarizeBy: none
		sourceColumn: Placa carreta 2

		annotation SummarizationSetBy = Automatic

	column 'Frota carreta 2'
		dataType: string
		lineageTag: 50485f0d-4e15-4109-8e79-d3a8a5d6a215
		summarizeBy: none
		sourceColumn: Frota carreta 2

		annotation SummarizationSetBy = Automatic

	column 'Nº rastreador cavalo'
		dataType: string
		lineageTag: c328d307-14fa-4066-9ed3-74a8e2d1f79e
		summarizeBy: none
		sourceColumn: Nº rastreador cavalo

		annotation SummarizationSetBy = Automatic

	column 'Emp. tecnologia cavalo'
		dataType: string
		lineageTag: 4ebc719c-a534-4a68-871f-45766ee9169e
		summarizeBy: none
		sourceColumn: Emp. tecnologia cavalo

		annotation SummarizationSetBy = Automatic

	column 'Nº rastreador carreta'
		dataType: string
		lineageTag: e4a607fe-ae30-41d1-8744-6b0f6ed31006
		summarizeBy: none
		sourceColumn: Nº rastreador carreta

		annotation SummarizationSetBy = Automatic

	column 'Emp. tecnologia carreta'
		dataType: string
		lineageTag: c81aa416-b081-4696-a500-e1d26b3f4e54
		summarizeBy: none
		sourceColumn: Emp. tecnologia carreta

		annotation SummarizationSetBy = Automatic

	column 'Última posição'
		dataType: string
		lineageTag: 9d6003bf-c8ec-4d6b-889c-5cf3804e59a9
		summarizeBy: none
		sourceColumn: Última posição

		annotation SummarizationSetBy = Automatic

	column 'Latitude última posição'
		dataType: string
		lineageTag: dffebd28-8b5d-4820-922b-d7a9e3bbf369
		summarizeBy: none
		sourceColumn: Latitude última posição

		annotation SummarizationSetBy = Automatic

	column 'Longitude última posição'
		dataType: string
		lineageTag: e3b23bb4-9f64-4016-be21-d4890c9f48ef
		summarizeBy: none
		sourceColumn: Longitude última posição

		annotation SummarizationSetBy = Automatic

	column 'Posição anterior'
		dataType: string
		lineageTag: 3843941f-b33c-492d-aa2e-d5ba1856428f
		summarizeBy: none
		sourceColumn: Posição anterior

		annotation SummarizationSetBy = Automatic

	column 'Latitude posição anterior'
		dataType: string
		lineageTag: 3400d8f0-b760-4f42-a945-99b9b42063f8
		summarizeBy: none
		sourceColumn: Latitude posição anterior

		annotation SummarizationSetBy = Automatic

	column 'Longitude posição anterior'
		dataType: string
		lineageTag: c515cd87-a074-4dc2-ba0e-e57428e19704
		summarizeBy: none
		sourceColumn: Longitude posição anterior

		annotation SummarizationSetBy = Automatic

	column 'CPF motorista'
		dataType: string
		lineageTag: 7e68d98d-2b9b-4c3f-9438-71f2a453b465
		summarizeBy: none
		sourceColumn: CPF motorista

		annotation SummarizationSetBy = Automatic

	column Motorista
		dataType: string
		lineageTag: 5a86cd76-8b94-4a06-8b5e-03d158a6b468
		summarizeBy: none
		sourceColumn: Motorista

		annotation SummarizationSetBy = Automatic

	column 'CPF motorista 2'
		dataType: string
		lineageTag: 0ec1c00f-3d67-4844-b1af-780e33eabc54
		summarizeBy: none
		sourceColumn: CPF motorista 2

		annotation SummarizationSetBy = Automatic

	column 'Motorista 2'
		dataType: string
		lineageTag: a33d30f4-d151-4101-bd80-d0484f4173c8
		summarizeBy: none
		sourceColumn: Motorista 2

		annotation SummarizationSetBy = Automatic

	column 'Cliente viagem'
		dataType: string
		lineageTag: d230fff7-452b-459a-83f3-936f53024748
		summarizeBy: none
		sourceColumn: Cliente viagem

		annotation SummarizationSetBy = Automatic

	column 'Valor carga (R$)'
		dataType: string
		lineageTag: 7b2e40ab-cd3c-4cb5-9274-5330fe1b397b
		summarizeBy: none
		sourceColumn: Valor carga (R$)

		annotation SummarizationSetBy = Automatic

	column 'Tipo monitoração'
		dataType: string
		lineageTag: 985ebfab-77a0-4ae4-8496-84c071da54c5
		summarizeBy: none
		sourceColumn: Tipo monitoração

		annotation SummarizationSetBy = Automatic

	column 'Cidade origem'
		dataType: string
		lineageTag: 857e4fe1-0305-4d76-9189-cd5eda956289
		summarizeBy: none
		sourceColumn: Cidade origem

		annotation SummarizationSetBy = Automatic

	column 'Cidade destino'
		dataType: string
		lineageTag: bd77b101-fdba-4a3d-b9fb-536221bfbd08
		summarizeBy: none
		sourceColumn: Cidade destino

		annotation SummarizationSetBy = Automatic

	column 'Situação viagem'
		dataType: string
		lineageTag: a6a5ea9c-bddb-408d-8e76-108aaecaea11
		summarizeBy: none
		sourceColumn: Situação viagem

		annotation SummarizationSetBy = Automatic

	column 'Tipo operação documento'
		dataType: string
		lineageTag: d245348a-faf5-4bb4-8f28-cfe75cf19ab7
		summarizeBy: none
		sourceColumn: Tipo operação documento

		annotation SummarizationSetBy = Automatic

	column 'Situação ignição'
		dataType: string
		lineageTag: 5fd3fe6a-f1fe-4b95-9d74-8ef89383ae8e
		summarizeBy: none
		sourceColumn: Situação ignição

		annotation SummarizationSetBy = Automatic

	column Direção
		dataType: string
		lineageTag: 71a302c8-99f9-48d3-8cac-cb2ba1f2cf54
		summarizeBy: none
		sourceColumn: Direção

		annotation SummarizationSetBy = Automatic

	column Posição
		dataType: string
		lineageTag: 1fddb75b-4d1a-4274-b8fa-67cc74078571
		summarizeBy: none
		sourceColumn: Posição

		annotation SummarizationSetBy = Automatic

	column 'Minha referência'
		dataType: string
		lineageTag: d23f21f5-2ad3-4b9b-ba48-0f58bc696f80
		summarizeBy: none
		sourceColumn: Minha referência

		annotation SummarizationSetBy = Automatic

	column 'Referência posição cidade'
		dataType: string
		lineageTag: 5b1703da-fd5e-48cf-ad8a-4f83d792f737
		summarizeBy: none
		sourceColumn: Referência posição cidade

		annotation SummarizationSetBy = Automatic

	column 'Previsão início(BRA)'
		dataType: string
		lineageTag: eaee7e41-a7f7-4d53-b7f8-b4ebb9d8172f
		summarizeBy: none
		sourceColumn: Previsão início(BRA)

		annotation SummarizationSetBy = Automatic

	column 'Previsão fim(BRA)'
		dataType: string
		lineageTag: 35e5c9f1-e9c8-4939-882e-adac17992d0c
		summarizeBy: none
		sourceColumn: Previsão fim(BRA)

		annotation SummarizationSetBy = Automatic

	column 'Inicio posição'
		dataType: string
		lineageTag: f6c9979f-20a5-4ff1-8684-36b3b1055707
		summarizeBy: none
		sourceColumn: Inicio posição

		annotation SummarizationSetBy = Automatic

	column Produto(s)
		dataType: string
		lineageTag: f64817fc-65a4-4306-bcf4-d47508e4a346
		summarizeBy: none
		sourceColumn: Produto(s)

		annotation SummarizationSetBy = Automatic

	column 'Última cidade de destino'
		dataType: string
		lineageTag: 2c4d2838-ee36-4e09-b98b-e238f4200bab
		summarizeBy: none
		sourceColumn: Última cidade de destino

		annotation SummarizationSetBy = Automatic

	column 'Situação do veículo'
		dataType: string
		lineageTag: caf5d36a-e5aa-4ee8-a825-a5f726c2b32f
		summarizeBy: none
		sourceColumn: Situação do veículo

		annotation SummarizationSetBy = Automatic

	column 'Tempo total de viagem'
		dataType: string
		lineageTag: 87bea0bb-a073-4cea-8f54-d1c0ca1e0c1d
		summarizeBy: none
		sourceColumn: Tempo total de viagem

		annotation SummarizationSetBy = Automatic

	column 'Km Prevista'
		dataType: int64
		formatString: 0
		lineageTag: 41834bfb-4662-451d-9370-7dcc2c86a4bd
		summarizeBy: sum
		sourceColumn: Km Prevista

		annotation SummarizationSetBy = Automatic

	column 'Km Restante'
		dataType: int64
		formatString: 0
		lineageTag: 10c174ba-9586-4d99-9aa5-e3ce624e6174
		summarizeBy: sum
		sourceColumn: Km Restante

		annotation SummarizationSetBy = Automatic

	column Alvo
		dataType: string
		lineageTag: 72550b52-e813-4a8c-af80-6033b54296e8
		summarizeBy: none
		sourceColumn: Alvo

		annotation SummarizationSetBy = Automatic

	column '% conclusão da viagem'
		dataType: string
		lineageTag: 8620da30-434d-4f0b-ab8c-7e1d89dbb612
		summarizeBy: none
		sourceColumn: % conclusão da viagem

		annotation SummarizationSetBy = Automatic

	column 'Tipo de alvo'
		dataType: string
		lineageTag: 2c4784e9-10d3-4c83-a2a7-e1a882887dc7
		summarizeBy: none
		sourceColumn: Tipo de alvo

		annotation SummarizationSetBy = Automatic

	column 'Data entrada alvo'
		dataType: string
		lineageTag: 60501568-f403-4073-a18b-61583b2dcce8
		summarizeBy: none
		sourceColumn: Data entrada alvo

		annotation SummarizationSetBy = Automatic

	column 'Tempo no alvo'
		dataType: string
		lineageTag: b657bfcf-d803-481d-9726-ea070755f896
		summarizeBy: none
		sourceColumn: Tempo no alvo

		annotation SummarizationSetBy = Automatic

	column 'Km Percorrida'
		dataType: int64
		formatString: 0
		lineageTag: f1add9f8-21b5-4b5b-85dd-e1c1aefc4f16
		summarizeBy: sum
		sourceColumn: Km Percorrida

		annotation SummarizationSetBy = Automatic

	column 'Tipo de cavalo'
		dataType: string
		lineageTag: c400633f-3467-4d69-812e-bf4708460df1
		summarizeBy: none
		sourceColumn: Tipo de cavalo

		annotation SummarizationSetBy = Automatic

	column 'Tipo de carreta 1'
		dataType: string
		lineageTag: f8cd5a42-ceea-4fa5-a258-ecaa8032d0f0
		summarizeBy: none
		sourceColumn: Tipo de carreta 1

		annotation SummarizationSetBy = Automatic

	column 'Tipo de carreta 2'
		dataType: string
		lineageTag: 7a807075-8fbb-4eea-9c3c-5861ba33f39e
		summarizeBy: none
		sourceColumn: Tipo de carreta 2

		annotation SummarizationSetBy = Automatic

	column 'Prox. destinatário'
		dataType: string
		lineageTag: 3c2b187c-1091-4b36-a3fc-2e322beecf4a
		summarizeBy: none
		sourceColumn: Prox. destinatário

		annotation SummarizationSetBy = Automatic

	column Documento
		dataType: string
		lineageTag: 804fac9c-eafb-48e4-8545-61c7f5c37c87
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column 'Cid. prox. destinatário'
		dataType: string
		lineageTag: e2b186e1-f7fb-49bf-96f3-498753aca7fa
		summarizeBy: none
		sourceColumn: Cid. prox. destinatário

		annotation SummarizationSetBy = Automatic

	column 'Km restante reta (1.18)'
		dataType: int64
		formatString: 0
		lineageTag: f55259fd-1d40-4150-9e9c-945bc4f21f1c
		summarizeBy: sum
		sourceColumn: Km restante reta (1.18)

		annotation SummarizationSetBy = Automatic

	column 'Estado destino'
		dataType: string
		lineageTag: fdfab711-b184-41aa-bfed-18e1a63bb213
		summarizeBy: none
		sourceColumn: Estado destino

		annotation SummarizationSetBy = Automatic

	column 'Estado posição'
		dataType: string
		lineageTag: 5bfa5293-26ca-4556-ba8e-3803d287ae49
		summarizeBy: none
		sourceColumn: Estado posição

		annotation SummarizationSetBy = Automatic

	column 'Sit. veículo'
		dataType: string
		lineageTag: 5627d9f9-7077-41eb-a043-1c9b4905efb8
		summarizeBy: none
		sourceColumn: Sit. veículo

		annotation SummarizationSetBy = Automatic

	column 'Operação do cliente'
		dataType: string
		lineageTag: 579a0608-cf67-4f7a-b217-756be075af27
		summarizeBy: none
		sourceColumn: Operação do cliente

		annotation SummarizationSetBy = Automatic

	column 'Unidade responsável'
		dataType: string
		lineageTag: 5d2893e8-8bab-4027-a1ef-8bed8bad8177
		summarizeBy: none
		sourceColumn: Unidade responsável

		annotation SummarizationSetBy = Automatic

	column 'Data início retorno'
		dataType: string
		lineageTag: 09725c38-fe73-4d90-ba26-ccd977e12020
		summarizeBy: none
		sourceColumn: Data início retorno

		annotation SummarizationSetBy = Automatic

	column 'Km total retorno'
		dataType: int64
		formatString: 0
		lineageTag: 67958325-5067-45c4-8780-80476305d91b
		summarizeBy: sum
		sourceColumn: Km total retorno

		annotation SummarizationSetBy = Automatic

	column 'Situação operação'
		dataType: string
		lineageTag: d4534dc8-5cc5-4c24-976a-6906e98caace
		summarizeBy: none
		sourceColumn: Situação operação

		annotation SummarizationSetBy = Automatic

	column Sheet
		dataType: string
		lineageTag: 4efe583a-9c1f-467d-8e6a-5ab5d78f6376
		summarizeBy: none
		sourceColumn: Sheet

		annotation SummarizationSetBy = Automatic

	column false
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6a9a8b38-2ecf-431a-aa39-e47f66a67f9d
		summarizeBy: none
		sourceColumn: false

		annotation SummarizationSetBy = Automatic

	column Painel_Monitoracao
		dataType: string
		lineageTag: 3056a892-5546-45e0-89cd-d134765279a9
		summarizeBy: none
		sourceColumn: Painel_Monitoracao

		annotation SummarizationSetBy = Automatic

	partition 'Opentech - Acomp - Veiculos - Monitoração' = m
		mode: import
		queryGroup: 'TABELAS PADRÃO'
		source =
				let
				    Fonte = Folder.Files("C:\Users\flavi\OneDrive\001\Opentech - Acomp - Veiculos - Monitoração"),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(Fonte, each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (9)", each #"Transformar Arquivo (9)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (9)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (9)", Table.ColumnNames(#"Transformar Arquivo (9)"(#"Arquivo de Amostra (9)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"Name", type text}, {"Data", type any}, {"Item", type text}, {"Kind", type text}, {"Hidden", type logical}}),
				    #"Data Expandido" = Table.ExpandTableColumn(#"Tipo Alterado", "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68"}, {"Data.Column1", "Data.Column2", "Data.Column3", "Data.Column4", "Data.Column5", "Data.Column6", "Data.Column7", "Data.Column8", "Data.Column9", "Data.Column10", "Data.Column11", "Data.Column12", "Data.Column13", "Data.Column14", "Data.Column15", "Data.Column16", "Data.Column17", "Data.Column18", "Data.Column19", "Data.Column20", "Data.Column21", "Data.Column22", "Data.Column23", "Data.Column24", "Data.Column25", "Data.Column26", "Data.Column27", "Data.Column28", "Data.Column29", "Data.Column30", "Data.Column31", "Data.Column32", "Data.Column33", "Data.Column34", "Data.Column35", "Data.Column36", "Data.Column37", "Data.Column38", "Data.Column39", "Data.Column40", "Data.Column41", "Data.Column42", "Data.Column43", "Data.Column44", "Data.Column45", "Data.Column46", "Data.Column47", "Data.Column48", "Data.Column49", "Data.Column50", "Data.Column51", "Data.Column52", "Data.Column53", "Data.Column54", "Data.Column55", "Data.Column56", "Data.Column57", "Data.Column58", "Data.Column59", "Data.Column60", "Data.Column61", "Data.Column62", "Data.Column63", "Data.Column64", "Data.Column65", "Data.Column66", "Data.Column67", "Data.Column68"}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Data Expandido",{"Data.Column1", "Data.Column2", "Data.Column3", "Data.Column4", "Data.Column5", "Data.Column6", "Data.Column7", "Data.Column8", "Data.Column9", "Data.Column10", "Data.Column11", "Data.Column12", "Data.Column13", "Data.Column14", "Data.Column15", "Data.Column16", "Data.Column17", "Data.Column18", "Data.Column19", "Data.Column20", "Data.Column21", "Data.Column22", "Data.Column23", "Data.Column24", "Data.Column25", "Data.Column26", "Data.Column27", "Data.Column28", "Data.Column29", "Data.Column30", "Data.Column31", "Data.Column32", "Data.Column33", "Data.Column34", "Data.Column35", "Data.Column36", "Data.Column37", "Data.Column38", "Data.Column39", "Data.Column40", "Data.Column41", "Data.Column42", "Data.Column43", "Data.Column44", "Data.Column45", "Data.Column46", "Data.Column47", "Data.Column48", "Data.Column49", "Data.Column50", "Data.Column51", "Data.Column52", "Data.Column53", "Data.Column54", "Data.Column55", "Data.Column56", "Data.Column57", "Data.Column58", "Data.Column59", "Data.Column60", "Data.Column61", "Data.Column62", "Data.Column63", "Data.Column64", "Data.Column65", "Data.Column66", "Data.Column67", "Data.Column68", "Item", "Kind", "Hidden"}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Outras Colunas Removidas", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Km Prevista", Int64.Type}, {"Km Restante", Int64.Type}, {"Km Percorrida", Int64.Type}, {"Km restante reta (1.18)", Int64.Type}, {"Km total retorno", Int64.Type}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

